CREATE TABLE md_user (
  ID         INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME       VARCHAR(10)                       NOT NULL,
  AGE        INT(3)                            NOT NULL,
  FACE       VARCHAR(50)                       NOT NULL,
  MOBILE     VARCHAR(11)                       NOT NULL,
  TYPE       ENUM ('1', '2')                   NOT NULL,
  LOGIN_CODE VARCHAR(15)                       NOT NULL,
  LOGIN_PWD  VARCHAR(32)                       NOT NULL
);
ALTER TABLE md_user CHANGE COLUMN LOGIN_PWD LOGIN_PASSWORD VARCHAR(32) NOT NULL;
ALTER TABLE md_user ADD  COLUMN SEX ENUM('1','2') NOT NULL ;
ALTER TABLE md_user ADD  COLUMN SAVE_DATE DATETIME NOT NULL;
ALTER TABLE md_user ADD  COLUMN SAVE_PERSON VARCHAR(15) NOT NULL;
ALTER TABLE md_user ADD  COLUMN UPDATE_DATE DATETIME NULL;
ALTER TABLE md_user ADD  COLUMN UPDATE_PERSON VARCHAR(15) NULL;
ALTER TABLE md_user ADD  COLUMN STATUS ENUM('1', '-1') NOT NULL COMMENT '1启用-1停用';


CREATE TABLE md_module (
  ID INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PID INT(8) NOT NULL,
  ORDER_NUM INT(2) NOT NULL,
  PATH VARCHAR(50) NOT NULL,
  TYPE ENUM('1', '2') NOT NULL COMMENT '1菜单2功能',
  STATUS ENUM('1','-1') NOT NULL COMMENT '1启用-1停用',
  SAVE_DATE DATETIME NOT NULL,
  SAVE_PERSON VARCHAR(15) NOT NULL,
  UPDATE_DATE DATETIME NULL,
  UPDATE_PERSON VARCHAR(15) NULL
)ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=UTF8;


CREATE TABLE md_res(
  ID INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  MODULE_ID INT(8) NOT NULL,
  ORDER_NUM INT(2) NOT NULL,
  PATH VARCHAR(50) NOT NULL,
  STATUS ENUM('1','-1') NOT NULL COMMENT '1启用-1停用',
  SAVE_DATE DATETIME NOT NULL,
  SAVE_PERSON VARCHAR(15) NOT NULL,
  UPDATE_DATE DATETIME NULL,
  UPDATE_PERSON VARCHAR(15) NULL
)ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=UTF8;


CREATE TABLE md_role (
  ID INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  STATUS ENUM('1','-1') NOT NULL COMMENT '1启用-1停用',
  SAVE_DATE DATETIME NOT NULL,
  SAVE_PERSON VARCHAR(15) NOT NULL,
  UPDATE_DATE DATETIME NULL,
  UPDATE_PERSON VARCHAR(15) NULL
)ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=UTF8;


CREATE TABLE md_role_auth (
  ID INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ROLE_ID INT(8) NOT NULL,
  AUTH_ID INT(8) NOT NULL,
  SAVE_DATE DATETIME NOT NULL,
  SAVE_PERSON VARCHAR(15) NOT NULL,
  UPDATE_DATE DATETIME NULL,
  UPDATE_PERSON VARCHAR(15) NULL
)ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=UTF8;

CREATE TABLE md_user_role (
  ID INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USER_ID INT(8) NOT NULL,
  ROLE_ID INT(8) NOT NULL,
  SAVE_DATE DATETIME NOT NULL,
  SAVE_PERSON VARCHAR(15) NOT NULL,
  UPDATE_DATE DATETIME NULL,
  UPDATE_PERSON VARCHAR(15) NULL
)ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=UTF8;